name: sewamotorapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_secure_storage: ^7.0.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Tambahkan bagian assets untuk mengakses gambar
  assets:
    - assets/images/honda_beat.png
    - assets/images/yamaha_nmax.png
    - assets/images/honda_vario.png
    - assets/images/Mio_M3.png
